config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :projects, except: [:show] do
    member do
      post :building
      get  :building_data_entry
      post :save_building_data_entry
      post :update_building_services
      post :update_building_system
      post :update_building_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :get_total_area_building
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/projects_pending'                   => 'projects#projects_pending',               as: :projects_pending
  get  '/projects/:id/building'              => 'projects#building_entry',                 as: :building_entry
  get  '/projects/:id/services'              => 'projects#project_building_services',      as: :project_building_services
  get  '/projects/:id/system'                => 'projects#project_building_system',        as: :project_building_system
  get  '/projects/:id/type'                  => 'projects#project_building_type',          as: :project_building_type
  get  '/projects/:id/destroy'               => 'projects#destroy_show',                   as: :project_destroy_show

  resources :tunnel_projects, except: [:show] do
    member do
      post :tunnel
      get  :tunnel_data_entry
      post :save_tunnel_data_entry
      post :update_tunnel_services
      post :update_tunnel_system
      post :update_tunnel_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/tunnel_projects_pending'            => 'tunnel_projects#projects_pending',        as: :tunnel_projects_pending
  get  '/tunnel_projects/:id/tunnel'         => 'tunnel_projects#tunnel_entry',            as: :tunnel_entry
  get  '/tunnel_projects/:id/services'       => 'tunnel_projects#project_tunnel_services', as: :project_tunnel_services
  get  '/tunnel_projects/:id/system'         => 'tunnel_projects#project_tunnel_system',   as: :project_tunnel_system
  get  '/tunnel_projects/:id/type'           => 'tunnel_projects#project_tunnel_type',     as: :project_tunnel_type
  get  '/tunnel_projects/:id/destroy'        => 'tunnel_projects#destroy_show',            as: :project_tunnel_destroy_show

  get  '/about_us'                           => 'home#about_us',                           as: :about_us
  get  '/contact_us'                         => 'home#contact_us',                         as: :contact_us
  post '/contact_us'                         => 'home#save_contact_us',                    as: :save_contact_us
  get  '/pricing'                            => 'home#pricing',                            as: :pricing
  get  '/help'                               => 'home#help',                               as: :help
  get  '/faq'                                => 'home#faq',                                as: :faq
  get  '/terms_and_conditions'               => 'home#terms_and_conditions',               as: :terms_and_conditions
  get  '/privacy_policy'                     => 'home#privacy_policy',                     as: :privacy_policy
  
  get  '/welcome'                            => 'users#welcome',                           as: :welcome
  get  '/dashboard'                          => 'users#dashboard',                         as: :dashboard
  get  '/quick_start'                        => 'users#quick_start',                       as: :quick_start
  get  '/quick_start/step1'                  => 'users#quick_start_step1',                 as: :quick_start_step1
  get  '/quick_start/step2'                  => 'users#quick_start_step2',                 as: :quick_start_step2
  get  '/quick_start/step3'                  => 'users#quick_start_step3',                 as: :quick_start_step3
  get  '/quick_start/download'               => 'users#download',                          as: :quick_start_download
  get  '/credits'                            => 'users#credits',                           as: :credits
  get  '/users/retrieve_password/new'        => 'users#retrieve_password',                 as: :retrieve_password
  post '/users/retrieve_password'            => 'users#retrieve_forgotten_password',       as: :retrieve_forgotten_password
  get  '/send_activation_email'              => 'users#send_activation_email',             as: :send_activation_email
  get  '/check_project_subscription'         => 'users#check_project_subscription',        as: :check_project_subscription
  get  '/check_username_unique'              => 'users#check_username_unique',             as: :check_username_unique
  get  '/check_current_username_unique'      => 'users#check_current_username_unique',     as: :check_current_username_unique
  get  '/check_email_unique'                 => 'users#check_email_unique',                as: :check_email_unique
  get  '/check_current_email_unique'         => 'users#check_current_email_unique',        as: :check_current_email_unique

  resources :subscriptions, only: [:create] do
    collection do
      post :plans
    end
  end

  # get '*path' => redirect('/')
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  devise_scope :user do
    authenticated :user do
      root to: "users#dashboard"
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  end
  
  # mount Ckeditor::Engine => '/ckeditor'
end

app/models/user.rb
class User < ActiveRecord::Base  
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, authentication_keys: [:login]

  ## Relations
  has_many :projects, dependent: :destroy
  has_many :tunnel_projects, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :building_plan, class_name: 'Plan', foreign_key: 'building_plan_id'
  belongs_to :tunnel_plan, class_name: 'Plan', foreign_key: 'tunnel_plan_id'

  ## Validations
  validates :first_name, :last_name, :user_name, :company_name, :phone_number, presence: true
  validates :user_name, uniqueness: { case_sensitive: false }, format: { with: /^[a-zA-Z0-9_\.]*$/, multiline: true }, exclusion: { in: %w(super super_admin admin user admin_user user_admin), message: "%{value} is taken." }
  validates :phone_number, length: { in: 8..15 }, numericality: { only_integer: true }
  # validates :password, format: { with: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$/, message: "must include one number, one uppercase letter and one lowercase letter.", multiline: true}, on: :create
  validates :terms_and_conditions, acceptance: true

  attr_accessor :login, :current_password

  ## Callbacks
  before_create :assign_default_values, :send_verification_email
  before_save :assign_full_name

  ## Class Methods
  def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions.to_h).where(["lower(user_name) = :value OR lower(email) = :value", { value: login.downcase }]).first
	  else
	    where(conditions.to_h).first
	  end
	end

  def self.user_email(email)
    self.where(email: email).last
  end

  def self.user_username(user_name)
    self.where(user_name: user_name).last
  end

  ## Instance Methods

  #this method is called by devise to check for "active" state of the model
  def active_for_authentication?
    super and !self.disable?
  end

  def assign_default_values
    self.building_quote_storage_date = Time.now
    self.tunnel_quote_storage_date = Time.now
    manage_credit = ManageCredit.last
    if manage_credit.present?
      self.credits = manage_credit.default_credits
    end
  end

  def send_verification_email
  	UserMailer.delay.verification(self.email)
  end

  def assign_full_name
    first_name = (self.first_name.present? ? self.first_name : "")
    last_name = (self.last_name.present? ? self.last_name : "")
    self.full_name = first_name + " " + last_name
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	respond_to :html, :js
	skip_before_action :trial_expired, only: [:edit]
	
  protected
		def update_resource(resource, params)
			if params[:password].present?
				result = resource.update_with_password(params)
				sign_in resource, bypass: true
			else
				result = resource.update_without_password(params)
			end
		end

	  def after_inactive_sign_up_path_for(resource)
	    new_user_session_path
	  end

	  def after_update_path_for(resource)
      edit_user_registration_path
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :html, :js
  skip_before_action :trial_expired, only: [:destroy]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## Filters
  before_action :authenticate_user!, except: [:send_activation_email, :retrieve_password, :retrieve_forgotten_password, :check_username_unique, :check_email_unique]
  before_action :set_first_param, only: [:welcome, :dashboard, :quick_start, :quick_start_step1, :quick_start_step2, :quick_start_step3]
  before_action :set_all_params, only: [:quick_start_step1, :quick_start_step2, :quick_start_step3]
  skip_before_action :trial_expired, only: [:welcome, :dashboard, :send_activation_email, :retrieve_password, :retrieve_forgotten_password, :check_username_unique, :check_current_username_unique, :check_email_unique, :check_current_email_unique]
  skip_before_action :set_static_page, only: [:send_activation_email, :check_username_unique, :check_current_username_unique, :check_email_unique, :check_current_email_unique]

  def welcome
  end

  def dashboard
    @credits = params[:credits]
    @expired = params[:expired]
  end

  def quick_start
  end

  def quick_start_step1
  end

  def quick_start_step2
  end

  def quick_start_step3
  end

  def download
  end

  def credits
    @page = params[:page].present? ? params[:page] : "1"
    @subscriptions = current_user.subscriptions.paginate(page: @page).order("id DESC")
  end

  def send_activation_email
    user = User.where(email: params[:email]).first
    if user.present?
      user.send_confirmation_instructions
      message = "You will receive an email with instructions for how to confirm your email address in a few minutes."
    else
    	message = "User not found."
    end
    redirect_to new_user_session_path, notice: message
  end

  def retrieve_password
    @user = User.new
  end

  def retrieve_forgotten_password
    login = params[:user][:login] rescue ""
    unless login.present?
      login = ""
    end
    user = User.where(["lower(user_name) = :value OR lower(email) = :value", { value: login.downcase }]).first
    if user.present?
      password = Devise.friendly_token.first(8)
      user.update(password: password)
    	UserMailer.delay.retrieve_password(user, password)
      redirect_to new_user_session_path, notice: "You will receive an email with your password in a few minutes."
    else
      redirect_to retrieve_password_path, notice: "Login not found."
    end
  end

  def check_project_subscription
    @authorized = true
    facility = params[:facility]
    if remaining_days <= 0 && !current_user.admin?
      if facility.present?
        if facility == "Building" && !current_user.building_plan.present?
          @authorized = false
        elsif facility == "Tunnel" && !current_user.tunnel_plan.present?
          @authorized = false
        end
      else
        @authorized = false
      end
    end
  end

  def check_username_unique
    user_name = params[:user][:user_name] rescue ""
    if user_name.present?
      user = User.user_username(user_name)
      if user.present?
        render json: false
      else
        if( (user_name == "super") || (user_name == "super_admin") || (user_name == "admin") || (user_name == "user") || (user_name == "admin_user") || (user_name == "user_admin") )
          render json: false
        else
          render json: true
        end
      end
    else
      render json: true
    end
  end

  def check_current_username_unique
    user_name = params[:user][:user_name] rescue ""
    if user_name.present?
      user = User.user_username(user_name)
      if user.present? && user.id != current_user.id
        render json: false
      else
        if( (user_name == "super") || (user_name == "super_admin") || (user_name == "admin") || (user_name == "user") || (user_name == "admin_user") || (user_name == "user_admin") )
          render json: false
        else
          render json: true
        end
      end
    else
      render json: true
    end
  end

  def check_email_unique
    email = params[:user][:email] rescue ""
    if email.present?
      user = User.user_email(params[:user][:email])
      if user.present?
        render json: false
      else
        render json: true
      end
    else
      render json: true
    end
  end

  def check_current_email_unique
    email = params[:user][:email] rescue ""
    if email.present?
      user = User.user_email(params[:user][:email])
      if user.present? && user.id != current_user.id
        render json: false
      else
        render json: true
      end
    else
      render json: true
    end
  end

  protected
    def set_first_param
      @first = 1 if params[:first].present?
    end

    def set_all_params
      @first = params[:first]
      @project_id = params[:project_id]
      @facility = params[:facility]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dashboard.html.erb
<% content_for(:title) do %>
  Dashboard
<% end %>

<% if static_page.present? && static_page.home_page.present? %>
  <%= static_page.home_page.html_safe %>
<% else %>
	<div class="grayOuter padding_50">
		<div class="container">
			<div class="stepInnerContnt dashboard">
				<div class="clearfix tac boldHD my-acc-edit"> Welcome to your Dashboard !</div>
				 <p class="dash_para m-plan">On this page you may access your Account to review details, change password, review and upgrade your subscription, payment details, and more. You also have access to all completed project report files available for download (subject to limitations, if any, of your subscription level). You also have access to the Quick-Start Guide, available for review whenever you need it. <br>
					<span>Click to access any of the areas below, or Click the Start Button to begin a new project </span>
				</p>
				<div class="row fastStart">
					<div class="col-sm-6">
						<div class="dash_start new_start">					
							<p>Click <%= link_to "Start", quick_start_step1_path(first: 1), remote: true %> Button to begin a <br> new project with help screens</p>
							<%= link_to "Start", quick_start_step1_path(first: 1), remote: true, class: "btn_start" %>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="dash_start fast_start">
							<p>Click <%= link_to "fast-start", new_project_path, remote: true %> Button to Begin A <br>new project without help screens</p>
							<%= link_to "fast-Start", new_project_path, remote: true, class: "btn_fast_start" %>
						</div>
					</div>
				</div>	
			</div>
			<div class="row">
				<div class="col-sm-3 col-xs-6 padd_rgt0">
					<div class="project_box border-credits bg-dashboard">
						<div class="dash_bg1">
							<%= link_to projects_path, remote: true, class: "projct" do %>
								<span></span>projects
							<% end %>
							<%= link_to projects_pending_path, remote: true, class: "p_pending" do %>
								<span></span>projects pending
							<% end %>
						</div>
					</div>
				</div>
				<div class="col-sm-3 padd_rgt0 col-xs-6">
					<div class="project_box border-credits bg-dashboard">
						<div class="dash_bg2 center_text bg-padding">
							<%= link_to edit_user_registration_path, remote: true, class: "icn_account" do %>
								<span></span>My Account
							<% end %>
							<p></p>
						</div>
					</div>
				</div>
				<div class="col-sm-3 padd_rgt0 col-xs-6">
					<div class="project_box border-credits bg-dashboard">
						<div class="dash_bg3">
							<%= link_to quick_start_path, remote: true, class: "q_start" do %>
								<span></span>Quick-Start guide
							<% end %>
							<%= link_to help_path, remote: true, class: "h_support" do %>
								<span></span>Help-support
							<% end %>
						</div>
					</div>
				</div>
				<div class="col-sm-3 col-xs-6 padd_rgt0">
					<div class="project_box border-credits bg-dashboard">
						<div class="dash_bg4 center_text">
							<span class="icn_report"></span>
							<%= link_to "javascript:;", class: "report_cust", data: {tooltip: "AVAILABLE IN PRO ACCOUNT ONLY"} do %>
								Report<br>customization
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

<!-- Credits Modal Start -->
<div class="modal fade" id="credits" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-md small-modal-margin">
	  <div class="modal-content text-center">
	    <div class="modal-header">
	      <h4 id="destroyShowLabel" class="modal-title">
	        You have <%= current_user.credits %> credits. Please buy credits to continue.
	      </h4>
	    </div>
	    <div class="modal-footer text-align-center btn_center margin-top-0">
	      <%= link_to "Buy Credits", credits_path, class: "btn_start padding-10" %>
	    </div>
	  </div>
	</div>
</div>
<!-- Credits Modal End -->

<!-- Expired Modal Start -->
<div class="modal fade" id="expired" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-md small-modal-margin">
	  <div class="modal-content text-center">
	    <div class="modal-header">
	      <h4 id="destroyShowLabel" class="modal-title">
	        Your trial period has expired. Please subscribe to continue.
	      </h4>
	    </div>
	    <div class="modal-footer text-align-center btn_center margin-top-0">
	      <%= link_to "Subscribe", pricing_path, class: "btn_start padding-10" %>
	    </div>
	  </div>
	</div>
</div>
<!-- Expired Modal End -->

<script type="text/javascript">
	document.title = "Dashboard"
	if (history && history.pushState) {
		history.pushState(null, document.title, "<%= root_path %>");
		$(window).bind("popstate", function(){
	    $.getScript(location.href);
	  });
	}
	<% if credits.present? && (credits == "0") %>
		$("#credits").modal("show");
	<% end %>
	<% if expired.present? && (expired == "1") %>
		$("#expired").modal("show");
	<% end %>
</script>

app/views/users/_quick_start.html.erb
<% content_for(:title) do %>
  Quick Start
<% end %>

<% if static_page.present? && static_page.quick_start.present? %>
  <%= static_page.quick_start.html_safe %>
<% else %>
	<div class="grayOuter">
		<div class="container">
			<div class="stepInnerContnt">
				<h1 class="clearfix tac boldHD quick_start_h1"> Quick-Start Guide</h1>
					<h2 class="grayMainGD">On this page you will find all the necessary information to enable you to get your projects started <br>
					and completed in the shortest time possible. </h2>
					<p>So, ignore the temptation to skip this section- you’ll be glad you did- and you’ll benefit immensely in the long run</p>
				<iframe  src="https://www.youtube.com/embed/6v2L2UGZJAM" allowfullscreen class="videoFrame" ></iframe>
			</div>
		</div>
	</div>
	<div class="Disclaimer whiteBkg">
		<div class="container">
			<div class="max960width">
				<div class="clearfix tac boldHD quick_start_h1"> How it works</div>
					<p>The software produces and delivers a rough order of magnitude (ROM) estimate of the Bill of Materials (BOM) for wireless signal coverage extension systems within Buildings or Tunnels in 3 easy steps.</p>
				<div class="row mt40">
					<div class="col-sm-4">
						<div class="box box1">
							<span>
								<div class="imageIcon"> <%= image_tag "1a.png", alt: "" %> <%= image_tag "1.png", alt: "", class: "numbers" %> </div>
							</span>
							<div class="bold">Step 1</div>
						  <div>Input building or tunnel data.</div>	
						</div>
					</div>
					<div class="col-sm-4">
						<div class="box box2">
							<span>
								<div class="imageIcon"> <%= image_tag "2b.png", alt: "" %> <%= image_tag "2.png", alt: "", class: "numbers" %> </div>
							</span>
							<div class="bold">Step 2</div>
							<div>Input system and target performance data as required.</div>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="box box3">
							<span><div class="imageIcon"> <%= image_tag "3c.png", alt: "" %> <%= image_tag "3.png", alt: "", class: "numbers" %> </div>
							</span>
							<div class="bold">Step 3</div>
							<div>Acknowledge the disclaimer and hit the "Next" button to get your report!</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

<div class="stepOuterNext stepOuterLast">
	<div class="container">
		<% if static_page.present? && static_page.quick_start_footer.present? %>
		  <%= static_page.quick_start_footer.html_safe %>
		<% else %>
			Now that you've gone through the quick-start introductory training, you're ready to rock!<br>
			Click the button and let's get started!
		<% end %>
		<div class="nextBtn mt20">
			<% if first.present? %>
				<%= link_to "Start Project", dashboard_path(first: 1), remote: true, class: "orangeBtn" %>
			<% else %>
				<%= link_to "Start Project", dashboard_path, remote: true, class: "orangeBtn" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_quick_start_step2.html.erb
<% content_for(:title) do %>
  Quick Start Step2
<% end %>

<% if static_page.present? && static_page.quick_start_step2.present? %>
  <%= static_page.quick_start_step2.html_safe %>
<% else %>
	<div class="grayOuter">
		<div class="container">
			<div class="stepInnerContnt">
				<div class="stepOuter">
					<span>
						<%= image_tag "s1g.png", alt: "Step 1" %>
						<%= image_tag "s2GrnL.png", alt: "Step 2", class: "middleImg" %>
						<%= image_tag "s3Gray.png", alt: "Step 3" %>
					</span>
				</div>
				<h1 class="grayMainGD">This is Step 2 - the second of three steps toward completion of your project. <br></h1>
				<p>In this step we enter the System Feed Method (Off-Air, or Direct-Feed) and Architecture (Fiber of Coaxial Cable). After your selections are made, click the <strong>NEXT</strong> button to continue.</p>
			</div>
		</div>
	</div>
<% end %>

<div class="stepOuterNext">
	<div class="container">
		<% if first.present? && project_id.present? %>
			Click the Next Button to begin Step 2
			<div class="nextBtn mt20">
				<% if facility == "Tunnel" %>
					<%= link_to "Back", project_tunnel_services_path(project_id, first: first, facility: facility), remote: true, class: "grayBtn" %> &nbsp;
					<%= link_to "Next", project_tunnel_system_path(project_id, first: first, facility: facility), remote: true, class: "orangeBtn" %>
				<% else %>
					<%= link_to "Back", project_building_services_path(project_id, first: first, facility: facility), remote: true, class: "grayBtn" %> &nbsp;
					<%= link_to "Next", project_building_system_path(project_id, first: first, facility: facility), remote: true, class: "orangeBtn" %>
				<% end %>
			</div>
		<% else %>
			Click the Next Button to begin Step 3
			<div class="nextBtn mt20">
				<%= link_to "Back", quick_start_step1_path, remote: true, class: "grayBtn" %> &nbsp;
				<%= link_to "Next", quick_start_step3_path, remote: true, class: "orangeBtn" %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/_quick_start_step3.html.erb
<% content_for(:title) do %>
  Quick Start Step3
<% end %>

<% if static_page.present? && static_page.quick_start_step3.present? %>
  <%= static_page.quick_start_step3.html_safe %>
<% else %>
	<div class="grayOuter">
		<div class="container">
			<div class="stepInnerContnt">
				<div class="stepOuter">
					<span>
						<%= image_tag "s1g.png", alt: "Step 1" %>
						<%= image_tag "s2GrnL.png", alt: "Step 2", class: "middleImg" %>
						<%= image_tag "s3orange.png", alt: "Step 3" %>
					</span>
				</div>
				<h1 class="grayMainGD">This is Step 3 - the third and final step toward completion of your project. Please acknowledge the Disclaimer below and click the FINISH button to proceed with generating your report.</h1>
				<p>This is a Material-only ROM/Budgetary Price Quotation. This quote represents our best assessment of the ROM material categories and quantities required to develop the DAS solution per minimum viable inputs (MVI) stated by the user. This quotes but may be subject to variations due to factors beyond our control. The accuracy of this ROM quote is limited to the confines of the accuracy and industry best practices relating to standards for Budget Estimates of -10% to +25%.</p>
			</div>
		</div>
	</div>
<% end %>

<% if first.present? && project_id.present? %>
	<% if static_page.present? && static_page.disclaimer_acknowledgement.present? %>
	  <%= static_page.disclaimer_acknowledgement.html_safe %>
	<% else %>
	  <div class="Disclaimer whiteBkg">
	    <div class="container">
	      <div class="max960width">
	        <div class="clearfix tac boldHD"> Disclaimer</div>
	        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</p>
	        <label><input type="checkbox" name="acknowledge" id="disclaimer_acknowledge"> I have read and acknowledge the above disclaimer.</label>
	      </div>
	    </div>
	  </div>
	  <!-- Disclaimer Acknowledge Modal -->
	  <div class="modal fade" id="acknowledge_show" tabindex="-1" role="dialog" aria-labelledby="DisclaimerShowLabel">
	    <div class="modal-dialog modal-sm small-modal-margin">
	      <div class="modal-content text-center">
	        <div class="modal-header">
	          <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
	          <h4 id="DisclaimerShowLabel" class="modal-title">You must acknowledge the above disclaimer.</h4>
	        </div>
	        <div class="modal-footer text-align-center btn_center margin-top-0">
	          <%= link_to "OK", "javascript:;", class: "btn_start padding-10 margin-right-0", data: {dismiss: "modal"} %>
	        </div>
	      </div>
	    </div>
	  </div>
	<% end %>
	<div class="stepOuterNext stepOuterLast">
		<div class="container">
			Click the Finish Button to get your Report!
			<div class="nextBtn mt20">
				<%= link_to "Finish", "javascript:;", class: "orangeBtn", id: "finish_btn" %>
				<% if facility == "Tunnel" %>
    			<%= link_to "", report_tunnel_project_path(project_id, first: first, facility: facility), remote: true, class: "hide", id: "finish_hide_btn" %>
    		<% else %>
    			<%= link_to "", report_project_path(project_id, first: first, facility: facility), remote: true, class: "hide", id: "finish_hide_btn" %>
    		<% end %>
				<script type="text/javascript">
				  $(function(){
				    $("#finish_btn").click(function(){
				      if($("#disclaimer_acknowledge").is(":checked") == true) {
				      	<% if facility == "Tunnel" %>
				        	$.post( "<%= update_disclaimer_tunnel_project_path(project_id) %>", { disclaimer_acknowledge: "true" });
				        <% else %>
				        	$.post( "<%= update_disclaimer_project_path(project_id) %>", { disclaimer_acknowledge: "true" });
				        <% end %>
				      } else {
				        $("#acknowledge_show").modal("show");
				      }
				    });
				  });
				</script>
			</div>
		</div>
	</div>
<% else %>
	<div class="stepOuterNext stepOuterLast">
		<div class="container">
			<div class="nextBtn mt20">
				<%= link_to "Back", quick_start_step2_path, remote: true, class: "grayBtn" %> &nbsp;
				<%= link_to "Finish", dashboard_path, remote: true, class: "orangeBtn" %>
			</div>
		</div>
	</div>
<% end %>

app/views/users/check_project_subscription.js.erb
<% unless @authorized %>
	$("#subscription").modal("show");
<% end %>

app/views/users/dashboard.js.erb
$("#container_content").html("<%= j(render partial: 'dashboard', locals: { static_page: @static_page, credits: @credits, expired: @expired }) %>");
document.title = "Dashboard"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= root_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/users/quick_start_step3.html.erb
<%= render partial: 'quick_start_step3', locals: { first: @first, facility: @facility, project_id: @project_id, static_page: @static_page } %>