config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :projects, except: [:show] do
    member do
      post :building
      get  :building_data_entry
      post :save_building_data_entry
      post :update_building_services
      post :update_building_system
      post :update_building_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :get_total_area_building
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/projects_pending'                   => 'projects#projects_pending',               as: :projects_pending
  get  '/projects/:id/building'              => 'projects#building_entry',                 as: :building_entry
  get  '/projects/:id/services'              => 'projects#project_building_services',      as: :project_building_services
  get  '/projects/:id/system'                => 'projects#project_building_system',        as: :project_building_system
  get  '/projects/:id/type'                  => 'projects#project_building_type',          as: :project_building_type
  get  '/projects/:id/destroy'               => 'projects#destroy_show',                   as: :project_destroy_show

  resources :tunnel_projects, except: [:show] do
    member do
      post :tunnel
      get  :tunnel_data_entry
      post :save_tunnel_data_entry
      post :update_tunnel_services
      post :update_tunnel_system
      post :update_tunnel_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/tunnel_projects_pending'            => 'tunnel_projects#projects_pending',        as: :tunnel_projects_pending
  get  '/tunnel_projects/:id/tunnel'         => 'tunnel_projects#tunnel_entry',            as: :tunnel_entry
  get  '/tunnel_projects/:id/services'       => 'tunnel_projects#project_tunnel_services', as: :project_tunnel_services
  get  '/tunnel_projects/:id/system'         => 'tunnel_projects#project_tunnel_system',   as: :project_tunnel_system
  get  '/tunnel_projects/:id/type'           => 'tunnel_projects#project_tunnel_type',     as: :project_tunnel_type
  get  '/tunnel_projects/:id/destroy'        => 'tunnel_projects#destroy_show',            as: :project_tunnel_destroy_show

  get  '/about_us'                           => 'home#about_us',                           as: :about_us
  get  '/contact_us'                         => 'home#contact_us',                         as: :contact_us
  post '/contact_us'                         => 'home#save_contact_us',                    as: :save_contact_us
  get  '/pricing'                            => 'home#pricing',                            as: :pricing
  get  '/help'                               => 'home#help',                               as: :help
  get  '/faq'                                => 'home#faq',                                as: :faq
  get  '/terms_and_conditions'               => 'home#terms_and_conditions',               as: :terms_and_conditions
  get  '/privacy_policy'                     => 'home#privacy_policy',                     as: :privacy_policy
  
  get  '/welcome'                            => 'users#welcome',                           as: :welcome
  get  '/dashboard'                          => 'users#dashboard',                         as: :dashboard
  get  '/quick_start'                        => 'users#quick_start',                       as: :quick_start
  get  '/quick_start/step1'                  => 'users#quick_start_step1',                 as: :quick_start_step1
  get  '/quick_start/step2'                  => 'users#quick_start_step2',                 as: :quick_start_step2
  get  '/quick_start/step3'                  => 'users#quick_start_step3',                 as: :quick_start_step3
  get  '/quick_start/download'               => 'users#download',                          as: :quick_start_download
  get  '/credits'                            => 'users#credits',                           as: :credits
  get  '/users/retrieve_password/new'        => 'users#retrieve_password',                 as: :retrieve_password
  post '/users/retrieve_password'            => 'users#retrieve_forgotten_password',       as: :retrieve_forgotten_password
  get  '/send_activation_email'              => 'users#send_activation_email',             as: :send_activation_email
  get  '/check_project_subscription'         => 'users#check_project_subscription',        as: :check_project_subscription
  get  '/check_username_unique'              => 'users#check_username_unique',             as: :check_username_unique
  get  '/check_current_username_unique'      => 'users#check_current_username_unique',     as: :check_current_username_unique
  get  '/check_email_unique'                 => 'users#check_email_unique',                as: :check_email_unique
  get  '/check_current_email_unique'         => 'users#check_current_email_unique',        as: :check_current_email_unique

  resources :subscriptions, only: [:create] do
    collection do
      post :plans
    end
  end

  # get '*path' => redirect('/')
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  devise_scope :user do
    authenticated :user do
      root to: "users#dashboard"
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  end
  
  # mount Ckeditor::Engine => '/ckeditor'
end

app/views/shared/_footer.html.erb
<% if static_page.present? && static_page.footer.present? %>
  <%= static_page.footer.html_safe %>
<% else %>
	<div class="clearfix"></div>
	<footer class="clearfix">
		<div class="container">
			<span>
				<%= link_to t('links.home'), root_path, remote: true %>
				<%= link_to t('links.about_us'), about_us_path, remote: true %>
				<%= link_to t('links.terms_of_use'), terms_and_conditions_path, remote: true %>
				<%= link_to t('links.privacy_policy'), privacy_policy_path, remote: true %>
				<%= link_to t('links.faq'), faq_path, remote: true %>
				<%= link_to t('links.contact_us'), contact_us_path, remote: true %>
			</span>
			<div class="copy"> <%= t('links.copyright', year: Time.now.year) %> </div>
		</div>
	</footer>

	<div class="ajax-loading">
	  <span>
	    <p id="please_wait"><strong>Please wait..</strong></p>
	    <p><i class="glyphicon glyphicon-refresh gly-spin" aria-hidden="true"></i></p>
	  </span>
	</div>
<% end %>

<% unless user_signed_in? %>
	<!-- Login Modal -->
	<div class="modal fade login" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-body">
	   			<div class="formOuter">
						<%= static_page.heading_login_details.try(:html_safe) %>
						<div class="row">
							<%= form_for(@new_user, url: user_session_path, html: {id: "login_popup"}) do |f| %>
								<div class="col-sm-12">
									<%= f.text_field :login, autofocus: true, required: true, placeholder: "User Name / Email Id", class: "form-control inputText mb5" %>
								</div>
								<div class="col-sm-12">
									<%= f.password_field :password, required: true, placeholder: "Password", class: "form-control inputText mb5 mt15" %>
								</div>
								<div class="col-sm-5 plz">
								  <label> <%= f.check_box :remember_me %> Remember me </label>
								</div>
								<div class="col-sm-7 prz">
								  <%= f.submit "Submit", class: "form-control inputText inputSub" %>
								</div>
							<% end %>
						</div>
					</div>
	      </div>
	    </div>
	  </div>
	</div>
	<!-- Login Modal End -->
<% end %>

<!-- 
<div>
	<span><%#= link_to t('links.about_us'), about_us_path, remote: true %></span>
	<span><%#= link_to t('links.terms_and_conditions'), terms_and_conditions_path, remote: true %></span>
	<span><%#= link_to t('links.privacy_policy'), privacy_policy_path, remote: true %></span>
	<span><%#= t('links.all_rights_reserved', year: Time.now.year) %></span>
</div>
 -->

app/views/shared/_header.html.erb
<!-- HeaderOuter -->
<header>
	<div class="container">
		<div class="row">
			<% if user_signed_in? %>
				<% if static_page.present? && static_page.header_logged_in.present? %>
				  <%= static_page.header_logged_in.html_safe %>
				<% else %>
					<div class="col-sm-4 logoOuter">
						<%= link_to root_path, class: "logo", remote: true do %>
							<%= image_tag "logo.png", alt: "Logo" %>
						<% end %>
					</div>
					<div class="col-sm-8">
						<div class="text-right alreadyMEm logoutOuter"> <%= link_to t('links.logout'), destroy_user_session_path, method: :delete, class: "signIn logout" %></div>
						<div class="nav">
							<ul>
								<li class="i1"> <%= link_to " ", root_path, remote: true %> </li>
								<li class="i2"> <%= link_to " ", projects_path, remote: true %> </li>
								<li class="i3"> <%= link_to " ", tunnel_projects_path, remote: true %> </li>
								<li class="i4"> <%= link_to " ", "#{edit_user_registration_path}#myplan", remote: true %> </li>
							</ul>
						</div>
					</div>
				<% end %>
			<% else %>
				<% if static_page.present? && static_page.header_not_logged_in.present? %>
				  <%= static_page.header_not_logged_in.html_safe %>
				<% else %>
					<div class="col-sm-4 logoOuter">
						<%= link_to root_path, class: "logo", remote: true do %>
							<%= image_tag "logo.png", alt: "Logo" %>
						<% end %>
					</div>
					<div class="col-sm-8">
						<div class="text-right alreadyMEm">Already a Member ? <%= link_to t('links.login'), "javascript:;", class: "signIn", data: {toggle: "modal", target: "#login"} %></div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</header>
<!-- HeaderOuter End-->

<!-- 
<ul>
	<li><%#= link_to t('links.home'), root_path, remote: true %></li>
	<li><%#= link_to t('links.about_us'), about_us_path, remote: true %></li>
	<li><%#= link_to t('links.pricing'), pricing_path, remote: true %></li>
	<li><%#= link_to t('links.forum'), '#'%></li>
	<li><%#= link_to t('links.training'), '#'%></li>
	<li><%#= link_to t('links.contact_us'), contact_us_path, remote: true %></li>
	<li><%#= link_to t('links.help'), help_path, remote: true %></li>
	<li><%#= link_to t('links.terms_and_conditions'), terms_and_conditions_path, remote: true %></li>
	<%# if user_signed_in? %>
		<li><%#= link_to t('links.edit_profile'), edit_user_registration_path, remote: true %></li>
	<%# end %>
</ul>

<div id="user_nav">
  <%# if user_signed_in? %>
    <%#= t('links.signed_as', user: current_user.email) %>
    <%#= link_to t('links.sign_out'), destroy_user_session_path, method: :delete %>
  <%# else %>
    <%#= link_to t('links.sign_up'), new_user_registration_path, remote: true %> or <%#= link_to t('links.sign_in'), new_user_session_path, remote: true %>
  <%# end %>
</div>
 -->

app/views/shared/_left_image.html.erb
<% if static_page.present? && static_page.left_image.present? && static_page.left_image.file.exists? %>
  <%= image_tag static_page.left_image.url, alt: "", class: "img-responsive" %>
<% else %>
  <%= image_tag "building_lft.jpg", alt: "", class: "img-responsive" %>
<% end %>

app/views/shared/_right_image.html.erb
<% if static_page.present? && static_page.right_image.present? && static_page.right_image.file.exists? %>
  <%= image_tag static_page.right_image.url, alt: "", class: "img-responsive" %>
<% else %>
  <%= image_tag "freedom.jpg", alt: "", class: "img-responsive" %>
<% end %>

app/views/shared/_slider_inner.html.erb
<% if static_page.present? && static_page.home_slider.present? %>
  <%= static_page.home_slider.html_safe %>
<% else %>
  <div class="col-sm-7">
    <div class="sliderInner">
      <h1 class="mainHD">NEVER WAIT</h1>  
      <div class="subHD">for another DAS Quote Estimate - Ever Again !</div>
      <%= image_tag "arrow.png", alt: "Arrow" %>
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <!-- Slide 1 Start -->
          <div class="item active">
            <div class="italic">Welcome to the world's first implementation of our time-tested Rapid System Design Assessment and Quote (RSDAQ™) method.</div>
          </div>
          <!-- Slide 1 End -->
          <!-- Slide 2 Start -->
          <div class="item">
            <div class="italic">Use our RSDAQ™ Engine and get the benefits of lightning-fast DAS Equipment Cost Estimates and BOMs generated simultaneously for up to 10 Buildings (and more) in less than 15 minutes - in 3 Easy Steps!</div>
          </div>
          <!-- Slide 2 End -->
          <!-- Slide 3 Start -->
          <div class="item">
            <div class="italic">12,185 Fast DAS ROM Quotes generated by the RSDAQ™ Engine to date, and counting!</div>
          </div>
          <!-- Slide 3 End -->
          <!-- Slide 4 Start -->
          <div class="item">
            <div class="italic">Extreme DAS ROM Quote ROI is now a reality !  The RSDAQ™ engine is unlike anything else available today for generating DAS ROM Quotes. Prove it for yourself !  Get your subscription and watch it drive your project ROI through the roof ! </div>
          </div>
          <!-- Slide 4 End -->
          </div>
        <!-- Controls -->
        <%= link_to "#carousel-example-generic", class: "left carousel-control", role: "button", data: {slide: "prev"} do %>
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
        <% end %>
        <%= link_to "#carousel-example-generic", class: "right carousel-control", role: "button", data: {slide: "next"} do %>
          <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/pdf_footer.html.erb
<div style="float:right;font-size:10px;color:#4f4f54;font-weight:bold;">
  Page <span class="page"></span> of <span class="topage"></span>
</div>

<script>
  function number_pages() {
    var vars={};
    var x=document.location.search.substring(1).split('&');
    for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = decodeURIComponent(z[1]);}
    var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
    for(var i in x) {
      var y = document.getElementsByClassName(x[i]);
      for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
    }
  }
  number_pages();
</script>