config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :projects, except: [:show] do
    member do
      post :building
      get  :building_data_entry
      post :save_building_data_entry
      post :update_building_services
      post :update_building_system
      post :update_building_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :get_total_area_building
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/projects_pending'                   => 'projects#projects_pending',               as: :projects_pending
  get  '/projects/:id/building'              => 'projects#building_entry',                 as: :building_entry
  get  '/projects/:id/services'              => 'projects#project_building_services',      as: :project_building_services
  get  '/projects/:id/system'                => 'projects#project_building_system',        as: :project_building_system
  get  '/projects/:id/type'                  => 'projects#project_building_type',          as: :project_building_type
  get  '/projects/:id/destroy'               => 'projects#destroy_show',                   as: :project_destroy_show

  resources :tunnel_projects, except: [:show] do
    member do
      post :tunnel
      get  :tunnel_data_entry
      post :save_tunnel_data_entry
      post :update_tunnel_services
      post :update_tunnel_system
      post :update_tunnel_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/tunnel_projects_pending'            => 'tunnel_projects#projects_pending',        as: :tunnel_projects_pending
  get  '/tunnel_projects/:id/tunnel'         => 'tunnel_projects#tunnel_entry',            as: :tunnel_entry
  get  '/tunnel_projects/:id/services'       => 'tunnel_projects#project_tunnel_services', as: :project_tunnel_services
  get  '/tunnel_projects/:id/system'         => 'tunnel_projects#project_tunnel_system',   as: :project_tunnel_system
  get  '/tunnel_projects/:id/type'           => 'tunnel_projects#project_tunnel_type',     as: :project_tunnel_type
  get  '/tunnel_projects/:id/destroy'        => 'tunnel_projects#destroy_show',            as: :project_tunnel_destroy_show

  get  '/about_us'                           => 'home#about_us',                           as: :about_us
  get  '/contact_us'                         => 'home#contact_us',                         as: :contact_us
  post '/contact_us'                         => 'home#save_contact_us',                    as: :save_contact_us
  get  '/pricing'                            => 'home#pricing',                            as: :pricing
  get  '/help'                               => 'home#help',                               as: :help
  get  '/faq'                                => 'home#faq',                                as: :faq
  get  '/terms_and_conditions'               => 'home#terms_and_conditions',               as: :terms_and_conditions
  get  '/privacy_policy'                     => 'home#privacy_policy',                     as: :privacy_policy
  
  get  '/welcome'                            => 'users#welcome',                           as: :welcome
  get  '/dashboard'                          => 'users#dashboard',                         as: :dashboard
  get  '/quick_start'                        => 'users#quick_start',                       as: :quick_start
  get  '/quick_start/step1'                  => 'users#quick_start_step1',                 as: :quick_start_step1
  get  '/quick_start/step2'                  => 'users#quick_start_step2',                 as: :quick_start_step2
  get  '/quick_start/step3'                  => 'users#quick_start_step3',                 as: :quick_start_step3
  get  '/quick_start/download'               => 'users#download',                          as: :quick_start_download
  get  '/credits'                            => 'users#credits',                           as: :credits
  get  '/users/retrieve_password/new'        => 'users#retrieve_password',                 as: :retrieve_password
  post '/users/retrieve_password'            => 'users#retrieve_forgotten_password',       as: :retrieve_forgotten_password
  get  '/send_activation_email'              => 'users#send_activation_email',             as: :send_activation_email
  get  '/check_project_subscription'         => 'users#check_project_subscription',        as: :check_project_subscription
  get  '/check_username_unique'              => 'users#check_username_unique',             as: :check_username_unique
  get  '/check_current_username_unique'      => 'users#check_current_username_unique',     as: :check_current_username_unique
  get  '/check_email_unique'                 => 'users#check_email_unique',                as: :check_email_unique
  get  '/check_current_email_unique'         => 'users#check_current_email_unique',        as: :check_current_email_unique

  resources :subscriptions, only: [:create] do
    collection do
      post :plans
    end
  end

  # get '*path' => redirect('/')
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  devise_scope :user do
    authenticated :user do
      root to: "users#dashboard"
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  end
  
  # mount Ckeditor::Engine => '/ckeditor'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  ## Filters
  before_action :authenticate_user!, only: [:pricing]
  skip_before_action :trial_expired
  skip_before_action :set_static_page, only: [:save_contact_us]

  def about_us
  end

  def pricing
  end

  def help
  end

  def terms_and_conditions
  end

  def contact_us
    @contact = Contact.new
  end

  def save_contact_us
    @message = ""
    @saved = false
    contact = Contact.new(contact_params)
    if contact.save
      UserMailer.delay.contact_us(contact)
      @saved = true
      @message = "We will get back to you soon."
    else
      @message = "Sorry please try again."
    end
  end

  def privacy_policy
  end

  private
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :contact_number, :message)
    end
end

app/helpers/home_helper.rb
module HomeHelper
	def building_yearly_plans(building_plan, static_page)
		message = "<td class='subs-type'>Annually</td>"
		building_plan_name = ""
		yearly = false
		if building_plan.present?
			building_plan_name = building_plan.name.split(" ").first
			yearly = building_plan.yearly
		end
		if building_plan_name == "Basic" && yearly
			message += "<td></td>
			<td><a href='javascript:;' data-href='#{static_page.building_standard_plan_link}' class='signUp subscribe'>Upgrade <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif building_plan_name == "Standard" && yearly
			message += "<td> </td>
			<td> </td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif building_plan_name == "Professional" && yearly
			message += "<td> </td>
			<td> </td>
			<td> </td>"
		else
			message += "<td><a href='javascript:;' data-href='#{static_page.building_basic_plan_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='javascript:;' data-href='#{static_page.building_standard_plan_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		end
		message
	end

	def building_monthly_plans(building_plan, static_page)
		message = "<td class='subs-type'>Monthly</td>"
		building_plan_name = ""
		yearly = true
		if building_plan.present?
			building_plan_name = building_plan.name.split(" ").first
			yearly = building_plan.yearly
		end
		if building_plan_name == "Basic" && !yearly
			message += "<td> </td>
			<td><a href='javascript:;' data-href='#{static_page.building_standard_plan_monthly_link}' class='signUp subscribe'>Upgrade <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif building_plan_name == "Standard" && !yearly
			message += "<td> </td>
			<td> </td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif building_plan_name == "Professional" && !yearly
			message += "<td> </td>
			<td> </td>
			<td> </td>"
		else
			message += "<td><a href='javascript:;' data-href='#{static_page.building_basic_plan_monthly_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='javascript:;' data-href='#{static_page.building_standard_plan_monthly_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		end
		message
	end

	def tunnel_yearly_plans(tunnel_plan, static_page)
		message = "<td class='subs-type'>Annually</td>"
		tunnel_plan_name = ""
		yearly = false
		if tunnel_plan.present?
			tunnel_plan_name = tunnel_plan.name.split(" ").first
			yearly = tunnel_plan.yearly
		end
		if tunnel_plan_name == "Basic" && yearly
			message += "<td> </td>
			<td><a href='javascript:;' data-href='#{static_page.tunnel_standard_plan_link}' class='signUp subscribe'>Upgrade <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif tunnel_plan_name == "Standard" && yearly
			message += "<td> </td>
			<td> </td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif tunnel_plan_name == "Professional" && yearly
			message += "<td> </td>
			<td> </td>
			<td> </td>"
		else
			message += "<td><a href='javascript:;' data-href='#{static_page.tunnel_basic_plan_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='javascript:;' data-href='#{static_page.tunnel_standard_plan_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		end
		message
	end

	def tunnel_monthly_plans(tunnel_plan, static_page)
		message = "<td class='subs-type'>Monthly</td>"
		tunnel_plan_name = ""
		yearly = true
		if tunnel_plan.present?
			tunnel_plan_name = tunnel_plan.name.split(" ").first
			yearly = tunnel_plan.yearly
		end
		if tunnel_plan_name == "Basic" && !yearly
			message += "<td> </td>
			<td><a href='javascript:;' data-href='#{static_page.tunnel_standard_plan_monthly_link}' class='signUp subscribe'>Upgrade <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif tunnel_plan_name == "Standard" && !yearly
			message += "<td> </td>
			<td> </td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		elsif tunnel_plan_name == "Professional" && !yearly
			message += "<td> </td>
			<td> </td>
			<td> </td>"
		else
			message += "<td><a href='javascript:;' data-href='#{static_page.tunnel_basic_plan_monthly_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='javascript:;' data-href='#{static_page.tunnel_standard_plan_monthly_link}' class='signUp subscribe w150'>Subscribe <img src='/assets/circleArror.png' alt=''></a></td>
			<td><a href='/contact_us' data-href='' class='signUp w170'>Contact Us <img src='/assets/circleArror.png' alt=''></a></td>"
		end
		message
	end
end

app/views/home/_contact_us.html.erb
<% content_for(:title) do %>
  Contact Us
<% end %>

<!--Start contact us-->
<% if static_page.present? && static_page.contact_us.present? %>
  <%= static_page.contact_us.html_safe %>
<% else %>
  <div class="contactMap">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55613461.81318646!2d-146.61479896957405!3d31.70561343684153!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x52b30b71698e729d%3A0x131328839761a382!2sNorth+America!5e0!3m2!1sen!2sin!4v1447843417347" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
  <div class="addressCon">
    <h1 class="quick_start_h1"> We are based in North America</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec lectus gravida, fringilla nunc id, cursus orci. Nulla efficitur ut tortor ac dapibus. Phasellus dignissim elementum diam eget tempor.</p>
    <ul>
      <li>
      	<%= image_tag "address.png", alt: "" %>
        <p>Consulting Lorem ipsum dolor sit amet.</p>
      </li>
      <li>
      	<%= image_tag "phone.png", alt: "" %>
        <p>(909) 949-9083</p>
       </li>
      <li>
      	<%= image_tag "email.png", alt: "" %>
        <p>info@example.com</p>
      </li>
    </ul>
  </div>
  <div class="formbox">
    <div class="formOuter">
      <div class="blackHD quick_start_h1">reach out to us today</div>
      <div class="row">
      	<%= form_for(contact, url: save_contact_us_path, method: :post, remote: true) do |f| %>
      		<div class="col-sm-12" id="message">
      			<div class="alert alert-info fade in margin-bottom-10">
      				<a data-dismiss="alert" class="close position-inherit">x</a>
      				<div id="return_message"></div>
      			</div>
      		</div>
          <div class="clearfix"></div>
  	      <div class="col-xs-6 prz">
  	        <%= f.text_field :first_name, autofocus: true, required: true, class: "form-control inputText mb5", placeholder: "First name" %>
  	      </div>
  	      <div class="col-xs-6 plz">
  	        <%= f.text_field :last_name, required: true, class: "form-control inputText mb5", placeholder: "Last name" %>
  	      </div>
          <div class="clearfix"></div>
  	      <div class="col-xs-6 prz">
  	        <%= f.email_field :email, required: true, class: "form-control inputText mb5 mt15", placeholder: "Email Address" %>
  	      </div>
  	      <div class="col-xs-6 plz">
  	        <%= f.text_field :contact_number, required: true, class: "form-control inputText mb5 mt15", placeholder: "Contact Number" %>
  	      </div>
          <div class="clearfix"></div>
  	      <div class="col-xs-12">
      			<%= f.text_area :message, required: true, class: "form-control inputText mb5 mt15", placeholder: "Enter Message" %>
  	      </div>
          <div class="clearfix"></div>
  	      <div class="col-xs-12">
  	        <%= f.submit class: "form-control inputText inputSub", value: "Submit" %>
  	      </div>
  	    <% end %>
      </div>
    </div>
  </div>
<% end %>
<!--End contact us-->

<script type="text/javascript">
  jQuery.validator.addMethod('phone', function(phone_number, element) {
    return this.optional(element) || phone_number.match(/^[0-9]\d*$/);
    });

  $(document).ready(function(){
    $("#new_contact").validate({
      errorPlacement: function(error, element) {
        error.insertAfter( element );
      },
      rules: {
        "contact[first_name]": {
          required: true,
          noSpace: true,
          maxlength: 125
        },
        "contact[last_name]": {
          required: true,
          noSpace: true,
          maxlength: 125
        },
        "contact[email]": {
          required: true,
          email: true,
          noSpace: true,
          maxlength: 255
        },
        "contact[contact_number]": {
          required: true,
          phone: true,
          minlength: 8,
          maxlength: 15
        },
        "contact[message]": {
          required: true,
          noSpace: true,
          minlength: 4,
          maxlength: 65000
        }
      },
      messages: {
        "contact[first_name]": {
          required: "Please enter your First Name.",
          noSpace: "Please enter valid First Name."
        },
        "contact[last_name]": {
          required: "Please enter your Last Name.",
          noSpace: "Please enter valid Last Name."
        },
        "contact[email]": {
          required: "Please enter your Email Address.",
          email: "Please enter valid Email Address.",
          noSpace: "Please enter valid Email Address."
        },
        "contact[contact_number]": {
          required: "Please enter your Contact Number.",
          phone: "Please enter valid Contact Number.",
          minlength: "Your Contact Number must be of minimum 8 digits.",
          maxlength: "Your Contact Number must be of maximum 15 digits."
        },
        "contact[message]": {
          required: "Please enter your Message.",
          noSpace: "Please enter valid Message.",
          minlength: "Your Message must contain minimum 4 characters."
        }
      },
      highlight: function (element) {
        $(element).parent().removeClass("has-success").addClass("has-error");
      },
      success: function (element) {
        $(element).parent().removeClass("has-error").addClass("has-success");
        $(element).removeClass("error");
        $(element).addClass("display-table margin-0");
      }
    });
  });
</script>

app/views/home/_privacy_policy.html.erb
<% content_for(:title) do %>
  Privacy Policy
<% end %>

<!--Start Privacy policy container-->
<% if static_page.present? && static_page.privacy_policy.present? %>
  <%= static_page.privacy_policy.html_safe %>
<% else %>
  <div class="innermainCon2">
    <div class="banrHd">
      <h1 align="left" class="quick_start_h1">Privacy Policy</h1>
    </div>
  	<div class="privacyCon">
  		<p align="left">This Privacy Policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our Privacy Policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.</p>

  	  <h2 align="left">1. What personal information do we collect from visitors to our website?</h2>
      <p align="left">When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, mailing address, phone number, Company Name or other details to help you with your experience.</p>

      <h2 align="left">2. Do we use 'cookies'?</h2>
      <p align="left">Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.</p>
      <p align="left">We use cookies to:<br>
        ■  Help remember and process the items in the shopping cart.<br>
        ■  Understand and save user's preferences for future visits.<br>
        ■  Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third party services that track this information on our behalf.
      </p>
      <p align="left">You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.</p>
      <p align="left">If you disable cookies off, some features will be disabled. It won't affect the users experience that make your site experience more efficient and some of our services will not function properly.
      However, you can still place orders.</p>

      <h2 align="left">3. How we use the Information we gather</h2>
      <p align="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec lectus gravida, fringilla nunc id, cursus orci. Nulla efficitur ut tortor ac dapibus. Phasellus dignissim elementum diam eget tempor. Donec massa eros, tristique sit amet varius sit amet, placerat vel mi. Curabitur tincidunt, tortor eget feugiat malesuada, elit nibh venenatis lacus, et tristique dolor lacus ut sapien. Morbi pharetra sodales lectus ac scelerisque. Nam sit amet quam in turpis efficitur ullamcorper. Sed tristique lorem lacus, rhoncus cursus nisl tempus vel.</p>
      <p align="left">Sed mauris quam, facilisis id lacus sed, fringilla pellentesque erat. Sed neque ipsum, lacinia in commodo vel, consequat in sem. Fusce id libero ac ante vehicula lobortis id sed tellus. Aliquam nulla nulla, tristique vitae suscipit a, ullamcorper at quam. In eu nibh maximus lorem mollis rhoncus. Sed feugiat, turpis et faucibus scelerisque, lorem lorem interdum ligula, vitae consequat urna eros pharetra nisl. Praesent sodales pulvinar magna. Nam eget metus ut purus porta vulputate vulputate a ligula. Ut et eros sem. Vivamus facilisis odio eget metus ornare, et varius augue bibendum. </p>
      <p align="left">Sed mauris quam, facilisis id lacus sed, fringilla pellentesque erat. Sed neque ipsum, lacinia in commodo vel, consequat in sem. Fusce id libero ac ante vehicula lobortis id sed tellus. Aliquam nulla nulla, tristique vitae suscipit a, ullamcorper at quam. In eu nibh maximus lorem mollis rhoncus. Sed feugiat, turpis et faucibus scelerisque, lorem lorem interdum ligula, vitae consequat urna eros pharetra nisl. Praesent sodales pulvinar magna. Nam eget metus ut purus porta vulputate vulputate a ligula. Ut et eros sem. Vivamus facilisis odio eget metus ornare, et varius augue bibendum. </p>

      <h2 align="left">4. Accessing, Reviewing and Changing your Personal Information</h2>
      <p align="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec lectus gravida, fringilla nunc id, cursus orci. Nulla efficitur ut tortor ac dapibus. Phasellus dignissim elementum diam eget tempor. Donec massa eros, tristique sit amet varius sit amet, placerat vel mi. Curabitur tincidunt, tortor eget feugiat malesuada, elit nibh venenatis lacus, et tristique dolor lacus ut sapien. Morbi pharetra sodales lectus ac scelerisque. Nam sit amet quam in turpis efficitur ullamcorper. Sed tristique lorem lacus, rhoncus cursus nisl tempus vel.</p>
      <p align="left">Sed mauris quam, facilisis id lacus sed, fringilla pellentesque erat. Sed neque ipsum, lacinia in commodo vel, consequat in sem. Fusce id libero ac ante vehicula lobortis id sed tellus. Aliquam nulla nulla, tristique vitae suscipit a, ullamcorper at quam. In eu nibh maximus lorem mollis rhoncus. Sed feugiat, turpis et faucibus scelerisque, lorem lorem interdum ligula, vitae consequat urna eros pharetra nisl. Praesent sodales pulvinar magna. Nam eget metus ut purus porta vulputate vulputate a ligula. Ut et eros sem. Vivamus facilisis odio eget metus ornare, et varius augue bibendum. </p>
      <p align="left">Sed mauris quam, facilisis id lacus sed, fringilla pellentesque erat. Sed neque ipsum, lacinia in commodo vel, consequat in sem. Fusce id libero ac ante vehicula lobortis id sed tellus. Aliquam nulla nulla, tristique vitae suscipit a, ullamcorper at quam. In eu nibh maximus lorem mollis rhoncus. Sed feugiat, turpis et faucibus scelerisque, lorem lorem interdum ligula, vitae consequat urna eros pharetra nisl. Praesent sodales pulvinar magna. Nam eget metus ut purus porta vulputate vulputate a ligula. Ut et eros sem. Vivamus facilisis odio eget metus ornare, et varius augue bibendum. </p>
  	</div>
  </div>
<% end %>
<!--End Privacy policy container-->

app/views/home/contact_us.html.erb
<%= render partial: 'contact_us', locals: { contact: @contact, static_page: @static_page } %>

app/views/home/help.html.erb
<%= render partial: 'help', locals: { static_page: @static_page } %>

app/views/home/help.js.erb
$("#container_content").html("<%= j(render partial: 'help', locals: { static_page: @static_page }) %>");
document.title = "Help Support"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= help_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

$(".faqCon strong").on("click", function(e){
  if($(this).parent().has("ul")) {
    e.preventDefault();
  }
  
  if(!$(this).hasClass("opens")) {
    // hide any open menus and remove all other classes
    $(".faqCon p").slideUp(350);
    $(".faqCon strong").removeClass("opens");
    
    // open our new menu and add the open class
    $(this).next("p").slideDown(350);
    $(this).addClass("opens");
  }
  
  else if($(this).hasClass("opens")) {
    $(this).removeClass("opens");
    $(this).next("p").slideUp(350);
  }
});

set_footer();
$('html').scrollTop(0);

app/views/home/pricing.html.erb
<%= render partial: 'pricing', locals: { static_page: @static_page } %>

app/views/home/pricing.js.erb
$("#container_content").html("<%= j(render partial: 'pricing', locals: { static_page: @static_page }) %>");
document.title = "Pricing"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= pricing_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/home/privacy_policy.html.erb
<%= render partial: 'privacy_policy', locals: { static_page: @static_page } %>

app/views/home/privacy_policy.js.erb
$("#container_content").html("<%= j(render partial: 'privacy_policy', locals: { static_page: @static_page }) %>");
document.title = "Privacy Policy"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= privacy_policy_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/home/save_contact_us.js.erb
$("#message").show();
$("#return_message").html("<%= @message %>");
<% if @saved %>
	$("#contact_first_name").val("");
	$("#contact_last_name").val("");
	$("#contact_email").val("");
	$("#contact_contact_number").val("");
	$("#contact_message").val("");
<% end %>

set_footer();

app/views/home/terms_and_conditions.js.erb
$("#container_content").html("<%= j(render partial: 'terms_and_conditions', locals: { static_page: @static_page }) %>");
document.title = "Terms of Use"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= terms_and_conditions_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);