config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :projects, except: [:show] do
    member do
      post :building
      get  :building_data_entry
      post :save_building_data_entry
      post :update_building_services
      post :update_building_system
      post :update_building_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :get_total_area_building
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/projects_pending'                   => 'projects#projects_pending',               as: :projects_pending
  get  '/projects/:id/building'              => 'projects#building_entry',                 as: :building_entry
  get  '/projects/:id/services'              => 'projects#project_building_services',      as: :project_building_services
  get  '/projects/:id/system'                => 'projects#project_building_system',        as: :project_building_system
  get  '/projects/:id/type'                  => 'projects#project_building_type',          as: :project_building_type
  get  '/projects/:id/destroy'               => 'projects#destroy_show',                   as: :project_destroy_show

  resources :tunnel_projects, except: [:show] do
    member do
      post :tunnel
      get  :tunnel_data_entry
      post :save_tunnel_data_entry
      post :update_tunnel_services
      post :update_tunnel_system
      post :update_tunnel_type
      get  :disclaimer
      post :update_disclaimer
      get  :report
      get  :show_generate_report
      get  :show_download_report
      get  :report_export
      get  :check_data_entries
      get  :check_system_architecture
    end
    collection do
      get  :get_floor_plan_message
    end
  end
  get  '/tunnel_projects_pending'            => 'tunnel_projects#projects_pending',        as: :tunnel_projects_pending
  get  '/tunnel_projects/:id/tunnel'         => 'tunnel_projects#tunnel_entry',            as: :tunnel_entry
  get  '/tunnel_projects/:id/services'       => 'tunnel_projects#project_tunnel_services', as: :project_tunnel_services
  get  '/tunnel_projects/:id/system'         => 'tunnel_projects#project_tunnel_system',   as: :project_tunnel_system
  get  '/tunnel_projects/:id/type'           => 'tunnel_projects#project_tunnel_type',     as: :project_tunnel_type
  get  '/tunnel_projects/:id/destroy'        => 'tunnel_projects#destroy_show',            as: :project_tunnel_destroy_show

  get  '/about_us'                           => 'home#about_us',                           as: :about_us
  get  '/contact_us'                         => 'home#contact_us',                         as: :contact_us
  post '/contact_us'                         => 'home#save_contact_us',                    as: :save_contact_us
  get  '/pricing'                            => 'home#pricing',                            as: :pricing
  get  '/help'                               => 'home#help',                               as: :help
  get  '/faq'                                => 'home#faq',                                as: :faq
  get  '/terms_and_conditions'               => 'home#terms_and_conditions',               as: :terms_and_conditions
  get  '/privacy_policy'                     => 'home#privacy_policy',                     as: :privacy_policy
  
  get  '/welcome'                            => 'users#welcome',                           as: :welcome
  get  '/dashboard'                          => 'users#dashboard',                         as: :dashboard
  get  '/quick_start'                        => 'users#quick_start',                       as: :quick_start
  get  '/quick_start/step1'                  => 'users#quick_start_step1',                 as: :quick_start_step1
  get  '/quick_start/step2'                  => 'users#quick_start_step2',                 as: :quick_start_step2
  get  '/quick_start/step3'                  => 'users#quick_start_step3',                 as: :quick_start_step3
  get  '/quick_start/download'               => 'users#download',                          as: :quick_start_download
  get  '/credits'                            => 'users#credits',                           as: :credits
  get  '/users/retrieve_password/new'        => 'users#retrieve_password',                 as: :retrieve_password
  post '/users/retrieve_password'            => 'users#retrieve_forgotten_password',       as: :retrieve_forgotten_password
  get  '/send_activation_email'              => 'users#send_activation_email',             as: :send_activation_email
  get  '/check_project_subscription'         => 'users#check_project_subscription',        as: :check_project_subscription
  get  '/check_username_unique'              => 'users#check_username_unique',             as: :check_username_unique
  get  '/check_current_username_unique'      => 'users#check_current_username_unique',     as: :check_current_username_unique
  get  '/check_email_unique'                 => 'users#check_email_unique',                as: :check_email_unique
  get  '/check_current_email_unique'         => 'users#check_current_email_unique',        as: :check_current_email_unique

  resources :subscriptions, only: [:create] do
    collection do
      post :plans
    end
  end

  # get '*path' => redirect('/')
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  devise_scope :user do
    authenticated :user do
      root to: "users#dashboard"
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  end
  
  # mount Ckeditor::Engine => '/ckeditor'
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def calculate_unit_price(project, product_price_list, part_quantity_information)
    price = product_price_list.our_sell_price.round(2)
    if (project.number_of_services >= 3) && (project.number_of_services <= 20)
      if part_quantity_information.report_material_list.present? && (part_quantity_information.report_material_list.material_category_id == 2)
        unit_multiplier = UnitMultiplier.last
        if unit_multiplier.present?
          price = price * unit_multiplier.multiplied_factor
        end
      end
    end
    price
  end

  def floor_plan_message(floor_plan)
    HaveFloorPlan.where(operator: floor_plan).first.try(:operand)
  end
  
	def name_project(project)
		if project.project_details?
      "#{link_to project.project_name, building_entry_path(project, facility: project.facility_option), remote: true}"
    elsif project.building_data?
      "#{link_to project.project_name, project_building_services_path(project, facility: project.facility_option), remote: true}"
    elsif project.building_services?
      "#{link_to project.project_name, project_building_system_path(project, facility: project.facility_option), remote: true}"
    elsif project.building_system?
      "#{link_to project.project_name, project_building_type_path(project, facility: project.facility_option), remote: true}"
    else
      "#{link_to project.project_name, edit_project_path(project, facility: project.facility_option), remote: true}"
    end
	end

	def edit_project(project)
		if project.project_details?
      "#{link_to '', building_entry_path(project, facility: project.facility_option), remote: true, class: 'glyphicon glyphicon-edit'}"
    elsif project.building_data?
      "#{link_to '', project_building_services_path(project, facility: project.facility_option), remote: true, class: 'glyphicon glyphicon-edit'}"
    elsif project.building_services?
      "#{link_to '', project_building_system_path(project, facility: project.facility_option), remote: true, class: 'glyphicon glyphicon-edit'}"
    elsif project.building_system?
      "#{link_to '', project_building_type_path(project, facility: project.facility_option), remote: true, class: 'glyphicon glyphicon-edit'}"
    else
      "#{link_to '', edit_project_path(project, facility: project.facility_option), remote: true, class: 'glyphicon glyphicon-edit'}"
    end
	end
end

app/views/projects/_building_system_form.html.erb
<% content_for(:title) do %>
  Project Details
<% end %>
<div class="grayOuter padding_50">
  <div class="container">
    <div class="building1">
      <div class="row">
        <div class="col-sm-3">
          <%= render partial: 'shared/left_image', locals: { static_page: static_page } %>
        </div>
        <div class="col-sm-6">
          <%= form_for(project, url: update_building_system_project_path(project), method: :post, remote: true, html: {id: "building_system_details"}) do |f| %>
            <%= hidden_field_tag :first, first %>
            <%= hidden_field_tag :facility, facility %>
            <div class="col-sm-12" id="error_messages"><%= model_error_messages(project) %></div>
            <div class="clearfix buildingStep2">
              <div class="col-md-6 col-xs-12 prFour padd_lft0">
                <div class="area_entry data_entry feed_method">
                  <%= static_page.building_system_feed_method.try(:html_safe) %>
                  <div class="inline_area radioLbl">
                    <% system_feed_methods.each do |system_feed| %>
                      <label>
                        <% if project.system_feed_method.present? %>
                          <%= f.radio_button :system_feed_method, system_feed.feed_method %> <%= system_feed.feed_method %>
                        <% else %>
                          <%= f.radio_button :system_feed_method, system_feed.feed_method, checked: system_feed.feed_assigned %> <%= system_feed.feed_method %>
                        <% end %>
                      </label>
                    <% end %>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
              <div class="plFour col-md-6 padd_rgt0 col-xs-12">
                <div class="area_entry data_entry feed_method">
                  <%= static_page.building_system_architecture.try(:html_safe) %>
                  <div class="inline_area radioLbl">
                    <% system_architectures.each do |system_archi| %>
                      <label>
                        <% if project.system_architecture.present? %>
                          <%= f.radio_button :system_architecture, system_archi.architecture, class: "system_architecture" %> <%= system_archi.architecture %>
                        <% else %>
                          <%= f.radio_button :system_architecture, system_archi.architecture, class: "system_architecture", checked: system_archi.architecture_assigned %> <%= system_archi.architecture %>
                        <% end %>
                      </label>
                    <% end %>
                  </div>
                  <%= link_to "Help", faq_path, class: "btn_cancel helpBtn", target: "_blank" %>
                </div>
              </div>
            </div>
            <div class="mt40 buildingQuoteB">
              <div class="b_data expected_rssi">
                <%= static_page.expected_rssi_at_mobile.try(:html_safe) %>
                <div class="text-center"></div>
                <div class="building_bx">
                  <div class="input_box inpbox">
                    <div class="selctFormBox">
                      <% if project.present? && project.expected_rssi_at_mobile.present? %>
                        <input type="text" value="<%= project.expected_rssi_at_mobile %>" readonly class="selectInput">
                      <% else %>
                        <input type="text" value="Select" readonly class="selectInput">
                      <% end %>
                      <%= f.select :expected_rssi_at_mobile, RssiThresholdLevelBenchmark.order("threshold_level DESC").collect {|rtlb| [ rtlb.threshold_level, rtlb.threshold_level ] }, { include_blank: false, prompt: "Select" }, class: "select" %>
                    </div>
                    <div class="question"><%= static_page.help_excepted_rssi_at_mobile.try(:html_safe) %></div>
                    <div class="radioLbl">
                      <label class="wauto small-fs13"><%= radio_button_tag "autoselect_rssi", "no", true, class: "autoselect_rssi" %> Auto Select (If you don't know)</label>
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>
            <div class="mt40 buildingQuoteB">
              <div class="b_data">
                <%= static_page.building_preferred_materials_sourcing.try(:html_safe) %>
                <div class="building_bx">
                  <div class="input_box inpbox">
                    <div class="selctFormBox">
                      <% if project.present? && project.marketing_id.present? %>
                        <input type="text" value="<%= Marketing.find_by_id(project.marketing_id).try(:vendor_name) %>" readonly class="selectInput">
                      <% else %>
                        <input type="text" value="Select" readonly class="selectInput">
                      <% end %>
                      <select id="project_marketing_id" name="project[marketing_id]" class="select">
                        <option value="">Select</option>
                        <% Region.eager_load(:marketings).all.each do |region| %>
                          <optgroup label="<%= region.name %>">
                            <% region.marketings.each do |marketing| %>
                              <% if project.marketing_id.present? && (project.marketing_id == marketing.id) %>
                                <option value="<%= marketing.id %>" selected><%= marketing.vendor_name %></option>
                              <% else %>
                                <option value="<%= marketing.id %>"><%= marketing.vendor_name %></option>
                              <% end %>
                            <% end %>
                          </optgroup>
                        <% end %>
                      </select>
                    </div>
                    <div class="question"><%= static_page.help_materials_sourcing.try(:html_safe) %></div>
                    <div class="radioLbl">
                      <label class="wauto small-fs13"><%= radio_button_tag "autoselect_vendor", "no", true, class: "autoselect_vendor" %> Auto Select (we can recommend where)</label>
                      <label class="wauto small-fs13"><%= radio_button_tag "autoselect_vendor", "not", false, class: "autoselect_vendor" %> Not Interested</label>
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
              <div class="btn_center">
                <%= link_to "Clear", "javascript:;", class: "btn_cancel", id: "clearform" %>
                <% if first.present? %>
                  <%= link_to "Back", quick_start_step2_path(project_id: project.slug, facility: facility, first: first), remote: true, class: "btn_back" %>
                <% else %>
                  <%= link_to "Back", project_building_services_path(project, facility: facility, first: first), remote: true, class: "btn_back" %>
                <% end %>
                <%= f.submit "Next", class: "btn_start btn-next" %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-sm-3">
          <div class="b_stepbox">
            <div class="stp_line"><span class="active"><div class="circle green_circle"></div></span><span class="active"></span><span class="active"></span></div>
            <div class="stp_line"><span class="lgreen_circle"><div class="circle lgreen_circle"></div></span></div>
            <div class="stp_line last"><span><div class="circle orange_circle"></div></span></div>
          </div>
          <%= image_tag "s2GrnL.png", alt: "", class: "step1" %>
          <%= render partial: 'shared/right_image', locals: { static_page: static_page } %>
        </div>
      </div>  
    </div>
  </div>
</div>

<!-- System Architecture Select Modal -->
<div class="modal fade" id="architecture_select" tabindex="-1" role="dialog" aria-labelledby="destroyShowLabel"></div>

<script type="text/javascript">
  $(function() {
    $('.select').change(function(){
      var a = $(this).find('option:selected').text();
      $(this).prev('.selectInput').val(a);
    });

    $('#clearform').click(function() {
      $("#building_system_details").get(0).reset();
    });

    $('.system_architecture').click(function(){
      if($(this).val() != "Auto Select"){
        $.get( "<%= check_system_architecture_project_path(project) %>", { system_architecture: $(this).val() });
      }
    });

    <% if project.marketing_id.present? %>
      $("#autoselect_vendor_no").attr("checked", false);
      $("#autoselect_vendor_not").attr("checked", false);
    <% end %>

    $("#project_marketing_id").change(function(){
      if($(this).val().length > 0) {
        $("#autoselect_vendor_no").attr("checked", false);
        $("#autoselect_vendor_not").attr("checked", false);
      } else {
        $("#autoselect_vendor_no").attr("checked", true);
        $("#autoselect_vendor_not").attr("checked", true);
        $("#autoselect_vendor_no").click();
        $("#autoselect_vendor_not").click();
      }
    });

    $(".autoselect_vendor").change(function(){
      if ($('input[name=autoselect_vendor]:checked').length > 0) {
        $("#project_marketing_id").val("")
        $(this).closest('.building_bx').find('.selectInput').val("Select");
      }
    });

    <% if project.expected_rssi_at_mobile.present? %>
      $("#autoselect_rssi_no").attr("checked", false);
    <% end %>

    $("#project_expected_rssi_at_mobile").change(function(){
      if($(this).val().length > 0) {
        $("#autoselect_rssi_no").attr("checked", false);
      } else {
        $("#autoselect_rssi_no").attr("checked", true);
        $("#autoselect_rssi_no").click();
      }
    });

    $(".autoselect_rssi").change(function(){
      if ($('input[name=autoselect_rssi]:checked').length > 0) {
        $("#project_expected_rssi_at_mobile").val("")
        $(this).closest('.building_bx').find('.selectInput').val("Select");
      }
    });
  });
</script>

app/views/projects/_show_download_report.html.erb
<div class="modal-dialog modal-md small-modal-margin">
  <div class="modal-content text-center">
    <div class="modal-header">
      <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
      <% if static_page.present? && static_page.download_warning.present? %>
        <%= static_page.download_warning.html_safe %>
      <% else %>
        <div class="Disclaimer">
          <div class="clearfix tac boldHD"> Notice</div>
          <p>The downloadable report below is provided for your use, as a subscriber to this service. Subletting of this account or resale of this report or service is strictly prohibited according to the terms of your subscription agreement.</p>
          <p>Violation of this notice will be subject to account termination.</p>
        </div>
      <% end %>
			<div class="nextBtn btn_center margin-top-0">
			  <%= link_to "Download", report_export_project_path(project), class: "orangeBtn padding-10-40", id: "report_export_download" %>
			</div>
      <div class="mt20"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $("#report_export_download").click(function() {
      $("#download_report").modal("hide");
    })
  })
</script>

app/views/projects/building_data_entry.js.erb
$("#dataEntry").html("<%= j(render partial: 'building_data_entry', locals: { project: @project, building: @building, building_data_entry: @building_data_entry, static_page: @static_page }) %>");
$("#dataEntry").modal({backdrop: 'static', keyboard: false});
setTimeout(function(){
	$("#building_data_entry_building_name").focus();
}, 1000);

app/views/projects/building_entry.js.erb
$("#container_content").html("<%= j(render partial: 'building_form', locals: { project: @project, building: @building, facility: @facility, first: @first, static_page: @static_page }) %>");
document.title = "Project Details"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= building_entry_path(@project, facility: @facility, first: @first) %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/projects/create.js.erb
<% if @saved %>
	<% if @project.facility_option == "Building" %>
		$("#container_content").html("<%= j(render partial: 'building_form', locals: { project: @project, building: @building, facility: @facility, first: @first, static_page: @static_page }) %>");
		document.title = "Project Details"
		if (history && history.pushState) {
			history.pushState(null, document.title, "<%= building_entry_path(@project, facility: @facility, first: @first) %>");
			$(window).bind("popstate", function() {
		    $.getScript(location.href);
		  });
		}
	<% elsif @project.facility_option == "Tunnel" %>
		$("#container_content").html("<%= j(render partial: 'tunnel_projects/tunnel_form', locals: { project: @project, tunnel: @tunnel, facility: @facility, first: @first, static_page: @static_page }) %>");
		document.title = "Project Details"
		if (history && history.pushState) {
			history.pushState(null, document.title, "<%= tunnel_entry_path(@project, facility: @facility, first: @first) %>");
			$(window).bind("popstate", function() {
		    $.getScript(location.href);
		  });
		}
	<% end %>
<% else %>
	<% if @authorized %>
		$("#error_messages").html("<%= j(model_error_messages(@project)) %>");
	<% end %>
<% end %>

set_footer();
$('html').scrollTop(0);

app/views/projects/destroy.js.erb
$("#destroy_show").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

<% if @discard %>
	$("#container_content").html("<%= j(render partial: 'form', locals: { project: Project.new, facility: @facility, first: @first, static_page: @static_page }) %>");
	document.title = "Project Details"
	if (history && history.pushState) {
		history.pushState(null, document.title, "<%= new_project_path %>");
		$(window).bind("popstate", function(){
	    $.getScript(location.href);
	  });
	}
<% else %>
	$("#container_content").html("<%= j(render partial: 'projects', locals: { projects: @projects, page: @page, static_page: @static_page }) %>");
	<% if @completed %>
		document.title = "Projects"
		if (history && history.pushState) {
			history.pushState(null, document.title, "<%= projects_path(page: @page) %>");
			$(window).bind("popstate", function(){
		    $.getScript(location.href);
		  });
		}
	<% else %>
		document.title = "Projects Pending"
		if (history && history.pushState) {
			history.pushState(null, document.title, "<%= projects_pending_path(page: @page) %>");
			$(window).bind("popstate", function(){
		    $.getScript(location.href);
		  });
		}
	<% end %>
<% end %>

set_footer();

app/views/projects/disclaimer.js.erb
$("#container_content").html("<%= j(render partial: 'disclaimer', locals: { project: @project, facility: @facility, static_page: @static_page }) %>");
document.title = "Disclaimer Acknowledgement"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= disclaimer_project_path(@project, facility: @facility) %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/projects/get_total_area_building.js.erb
$("#total_building_area").val("<%= @total %>");

app/views/projects/index.html.erb
<%= render partial: 'projects', locals: { projects: @projects, page: @page, static_page: @static_page } %>

app/views/projects/projects_pending.html.erb
<%= render partial: 'projects', locals: { projects: @projects, page: @page, static_page: @static_page } %>

app/views/projects/report.js.erb
$("#container_content").html("<%= j(render partial: 'report', locals: { project: @project, building_plan: @building_plan, timer_setting: @timer_setting, static_page: @static_page }) %>");
document.title = "Project Report"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= report_project_path(@project, first: @first, facility: @facility) %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/projects/update.js.erb
<% if @saved %>
	$("#container_content").html("<%= j(render partial: 'building_form', locals: { project: @project, building: @building, facility: @facility, first: @first, static_page: @static_page }) %>");
	document.title = "Project Details"
	if (history && history.pushState) {
		history.pushState(null, document.title, "<%= building_entry_path(@project, facility: @facility, first: @first) %>");
		$(window).bind("popstate", function() {
	    $.getScript(location.href);
	  });
	}
<% else %>
	$("#error_messages").html("<%= j(model_error_messages(@project)) %>");
<% end %>

set_footer();
$('html').scrollTop(0);

app/views/projects/update_building_services.js.erb
<% if @saved %>
	<% if @first.present? %>
		$("#container_content").html("<%= j(render partial: 'users/quick_start_step2', locals: { project_id: @project.slug, first: @first, facility: @facility, static_page: @static_page }) %>");
		document.title = "Step2"
		if (history && history.pushState) {
			history.pushState(null, document.title, "<%= quick_start_step2_path(project_id: @project.slug, first: @first, facility: @facility) %>");
			$(window).bind("popstate", function(){
		    $.getScript(location.href);
		  });
		}
	<% else %>
		$("#container_content").html("<%= j(render partial: 'building_system_form', locals: { project: @project, system_feed_methods: @system_feed_methods, system_architectures: @system_architectures, first: @first, facility: @facility, static_page: @static_page }) %>");
		document.title = "Project Details"
		if (history && history.pushState) {
			history.pushState(null, document.title, "<%= project_building_system_path(@project, first: @first, facility: @facility) %>");
			$(window).bind("popstate", function() {
		    $.getScript(location.href);
		  });
		}
	<% end %>
<% else %>
	$("#error_messages").html("<%= j(model_error_messages(@project)) %>");
<% end %>

set_footer();
$('html').scrollTop(0);

app/views/projects/update_disclaimer.js.erb
<% if @saved %>
	$("#finish_hide_btn").click();
<% end %>